/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'grant' at '3/5/17 11:41 AM' with Gradle 2.13
 *
 * @author grant, @date 3/5/17 11:41 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
